name = "title-review-checker"
main = "app.py"
compatibility_date = "2024-03-01"

[env.production.vars]
# 在 Cloudflare Workers 面板中设置这些环境变量
# GOOGLE_API_KEY = "your-api-key-here"
# SECRET_KEY = "your-secret-key-here"

[[env.production.kv_namespaces]]
binding = "TEMP_STORAGE"
id = "your-kv-namespace-id"

[build]
command = "pip install -r requirements.txt"

[vars]
ENVIRONMENT = "production"